#!/bin/bash

case "$1" in
  'configure')
    ln -s /usr/local/share/gherkin/gherkin /usr/local/bin/gherkin
    ln -s /usr/local/share/gherkin/gherkin-session /usr/local/bin/gherkin-session
  ;;
  'remove'|'purge'|'upgrade')
    [ -f /usr/local/bin/gherkin ] && rm /usr/local/bin/gherkin
    [ -f /usr/local/bin/gherkin-session ] && rm /usr/local/bin/gherkin-session
  ;;
esac
